#!/usr/bin/env bash

installran(){
   git clone https://github.com/m3ng9i/ran
   cd ran && sudo go install
   rm -rf ran
}


open -na Google\ Chrome --args --auto-open-devtools-for-tabs --disable-web-security --user-data-dir="/tmp/chrome_dev"
ran -r dist -p 8080
